### ISSUE TITLE
Installation and demo

### ISSUE THREAD

**Issue by alexbagirov** [jcpwfloi/cboj#1]
Hello!

Do you have a demo?

How to install your script?

**Comment by hczhcz** [comment]
The site is deployed at [codebursts.com](https://www.codebursts.com/).

**Comment by jcpwfloi** [comment]
The installation script and multi-language support will be updated in the future release. The demo is https://www.codebursts.com/

**Comment by alexbagirov** [comment]
When are you going to release an update?

**Comment by jcpwfloi** [comment]
It'll be released in about a month. The version will be cboj v2 alpha.

**Comment by alexbagirov** [comment]
Is it possible to deploy the app to Heroku?

**Comment by jcpwfloi** [comment]
If the PaaS provides the support of `build-essential` package, that'll be possible to deploy it in such platform. That means if `g++` command can be run on that platform, you can deploy it on it.

**Comment by alexbagirov** [comment]
Ok, will be waiting for your update and new instructions.

**Comment by alexbagirov** [comment]
Oh, and I want to ask you if it is possible for you to help me with installation of your script later. Can you?

**Comment by jcpwfloi** [comment]
Okay
